name: Test Flux C Examples

on:
  
  # Test Nightly
  schedule: 
  - cron: 0 0 * * 0
  # Test on pull request
  pull_request: []

jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/converged-computing/flux-c-examples
      options: --user root
    name: Build
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Bats
      run: apt-get update && apt-get install -y bats

    - name: Test Build
      run: make

    - name: Run Tests
      run: make test
